[package]
name = "lottery"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.9.1"
openzeppelin = "0.20.0"
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.33.0" }
assert_macros = "2.9.1"

[[target.starknet-contract]]
sierra = true
casm = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
block_id.tag = "latest"

[scripts]
test = "snforge test"